DATA:
  FEATURE_ROOT: 'xxx/xxx/xx/TCGA-LUNG-Feature-Path'
  TRAIN_VALID_CSV: './data/TCGA-LUNG/TCGA_LUNG_trainval.csv'
  TEST_CSV: './data/TCGA-LUNG/TCGA_LUNG_test.csv'

MODEL:
  FEATURE_DIM: 1024
  NUM_CLASS: 3
  POS_DIM: 128
  LATER_DIM: 512
  MASK_RATIO: 0.25
  LOSS_WEIGHT: 0.5
  RETURN_ATTE: False
  RETURN_PRED_COORDINATES: False
  RETURN_POS_ERROR: False

TRAIN:
  MAX_EPOCH: 100
  BATCH_SIZE: 1
  WORKERS: 12
  LR: 0.0005
  WEIGHT_DECAY: 0.00001
  WEIGHTS_SAVE_PATH: './save'